### ISSUE TITLE
Allow libsass options to be passed through to sass.js

### ISSUE THREAD

**Issue by KarlPurk** [KevCJones/plugin-scss#1]
It would be nice if plugin-scss allowed for libass options to be specified in your system config.

This would allow the user to configure libsass for their needs, for example, allowing them to provide includePaths for sass imports.

**Comment by kevcjones-archived** [comment]
Yes, yes it would... i will look into this.

**Comment by kevcjones-archived** [comment]
from what i can tell from first glances, i'm using sass.js which is for running / compiling sass in the browser, as opposed to libsass (node-sass). I'm digging around to see if it has a similar supported 'includePaths' option before i consider rolling my own solution

**Comment by kevcjones-archived** [comment]
So as i suspected sass.js isn't really made to work the same, transpiling in the browser i do not see any 'multiple' path support. But fear not... I have a suggestion

extract from SystemJS config

```
...
paths: {
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*",
    "styles*" : "src/styles*"
  },
```

Then you can use the @import format 

```
@import "jspm:styles/common/colors";
```

instead perhaps where you might be doing in a nested folder.

```
@import "../../../styles/common/colors";
```

This is good in fact because moving a component you can move the component to a different folder depth. Its just a configuration change.

**Comment by kevcjones-archived** [comment]
This is now done.
[Related to](https://github.com/KevCJones/plugin-scss/issues/5)
